package com.trip

import com.trip.*
 
rule "R1"
    when
        $ville: DescriptionVille(typeVille.contains("belle"))
        DescriptionActivite(restaurant.contains("Très bon"));
    then
        insert(new Avis($ville.getNomVille(),"méritant le détour"));
end

rule "R2"
    when
        $ville: DescriptionVille(typeVille.contains("historique"))
    then
        insert(new Avis($ville.getNomVille(),"méritant le détour"));
end

rule "R3"
    when
        $ville: DescriptionHabitant(accueillant && traditionFolklorique)
    then
        insert(new Avis($ville.getNomVille(),"méritant le détour"));
end

rule "R4"
    when
        $ville: DescriptionVille(monuments && vegetationAbondante)
    then
        insert(new Avis($ville.getNomVille(),"méritant le détour"));
end

rule "R5" lock-on-active
    when
        $a: DescriptionActivite($b : nomVille)
        DescriptionHabitant(nomVille == $b && traditionCulinaire)
    then
        modify($a){setRestaurant("bon restaurant")};
end

rule "R6" lock-on-active
    when
        $b: DescriptionActivite(nombreEtoiles == 3)
    then
        System.out.println("Infinite");
        $b.setRestaurant("Très bon restaurant");
        update($b);
end



 